name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # Activate the virtual environment
      - name: Activate virtual environment
        run: |
          # source /path/to/your/virtual/environment/bin/activate
          # C:\Program Files\Python311
          source C:\Program Files\Python311
          

      # Run your script with activated environment
      - name: Send Email
        env:
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: python send_email_script.py
