name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # python -m pip install -r requirements.txt
          C:\Program Files\Python311\python.exe -m pip install -r requirements.txt

      # Activate the virtual environment (if applicable)
      # No virtual environment needed for this case, directly use Python interpreter
      - name: Activate virtual environment
        run: |
          # Use the Python interpreter directly to install dependencies
          C:\Program Files\Python311\python.exe -m pip install -r requirements.txt

      # Print directory contents (for debugging)
      - name: Print directory contents
        run: ls -l

      # Run your script with activated environment
      - name: Send Email
        env:
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: python send_email_script.py
