name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade pip
          pip install <dependency1> <dependency2> <...>
          pip install --upgrade pip

      - name: Install dependencies from requirements.txt
        working-directory: ${{ github.workspace }}
        run: pip install -r requirements.txt

      - name: List directory contents
        run: ls -l

      - name: Send Email
        env:
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 587
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: python send_email_script.py
